[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[metadata]
name = "unit-db-test"
description = "Unittest wrapper focused on making DB integrity tests"
readme = "README.md"
license = "MIT"
author = "Mikel Cortes | @cortze"
author-email = "cortze@protonmail.com"
maintainer = "Mikel Cortes | @cortze"
maintainer-email = "cortze@protonmail.com"
url = "https://github.com/cortze/unit-db-test"

[project]
requires-python = ">=3.8"
dependencies = [
    'dotenv',
    'unittest',
    'psycopg2-binary',
    'sqlalchemy',
    'pandas',
]

[tool.setuptools_scm]
version = true

[project.urls]
Repository = "https://github.com/cortze/unit-db-test"

[tool.setuptools.packages.find]
include = [
  "unit_db_test*",
]